<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdminRepository::class)]
class Admin extends User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $FullName;

    public function getId(): ?int
    {
         return parent::getId();
    }

    public function getName(): ?string
    {
        return $this->FullName;
    }

    public function setName(string $FullName): self
    {
        $this->FullName = $FullName;

        return $this;
    }

    public function getLogin(): ?string
    {
        return parent::getLogin(); // TODO: Change the autogenerated stub
    }

    public function setLogin(string $Login): User
    {
        return parent::setLogin($Login); // TODO: Change the autogenerated stub
    }

    public function getPassword(): ?string
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    public function setPassword(string $Password): User
    {
        return parent::setPassword($Password); // TODO: Change the autogenerated stub
    }

    public function getCin(): ?string
    {
        return parent::getCin(); // TODO: Change the autogenerated stub
    }

    public function setCin(string $Cin): User
    {
        return parent::setCin($Cin); // TODO: Change the autogenerated stub
    }

    public function getRoles(): ?string
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }

    public function setRoles(string $roles): User
    {
        return parent::setRoles($roles); // TODO: Change the autogenerated stub
    }
}
