<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OperationRepository::class)]
class Operation extends Appointment
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $Type;

    #[ORM\ManyToOne(targetEntity: Room::class, inversedBy: 'Operations')]
    private $Room;

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getDate(): ?\DateTimeInterface
    {
        return parent::getDate(); // TODO: Change the autogenerated stub
    }

    public function setDate(\DateTimeInterface $Date): Appointment
    {
        return parent::setDate($Date); // TODO: Change the autogenerated stub
    }

    public function getDoctor(): ?Doctor
    {
        return parent::getDoctor(); // TODO: Change the autogenerated stub
    }

  
    public function getPatient(): ?Patient
    {
        return parent::getPatient(); // TODO: Change the autogenerated stub
    }

    


    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->Room;
    }

    public function setRoom(?Room $Room): self
    {
        $this->Room = $Room;

        return $this;
    }
}
