<?php

namespace App\Entity;

use App\Repository\PatientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PatientRepository::class)]
class Patient extends User
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $FirstName;

    #[ORM\Column(type: 'string', length: 255)]
    private $LastName;


    #[ORM\OneToMany(mappedBy: 'Patient', targetEntity: Observation::class)]
    private $observations;

    #[ORM\OneToMany(mappedBy: 'Patient', targetEntity: Appointment::class)]
    private $appointments;

    public function getId(): ?int
    {
        return parent::getId();
    }

    public function getLogin(): ?string
    {
        return parent::getLogin(); // TODO: Change the autogenerated stub
    }

    public function setLogin(string $Login): User
    {
        return parent::setLogin($Login); // TODO: Change the autogenerated stub
    }

    public function getPassword(): ?string
    {
        return parent::getPassword(); // TODO: Change the autogenerated stub
    }

    public function setPassword(string $Password): User
    {
        return parent::setPassword($Password); // TODO: Change the autogenerated stub
    }

    public function getCin(): ?string
    {
        return parent::getCin(); // TODO: Change the autogenerated stub
    }

    public function setCin(string $Cin): User
    {
        return parent::setCin($Cin); // TODO: Change the autogenerated stub
    }

    public function getRoles(): ?string
    {
        return parent::getRoles(); // TODO: Change the autogenerated stub
    }

    public function setRoles(string $roles): User
    {
        return parent::setRoles($roles); // TODO: Change the autogenerated stub
    }
    public function __construct()
    {
        $this->observations = new ArrayCollection();
        $this->appointments = new ArrayCollection();
    }



    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    /**
     * @return Collection<int, Observation>
     */
    public function getObservations(): Collection
    {
        return $this->observations;
    }

    public function addObservation(Observation $observation): self
    {
        if (!$this->observations->contains($observation)) {
            $this->observations[] = $observation;
            $observation->setPatient($this);
        }

        return $this;
    }

    public function removeObservation(Observation $observation): self
    {
        if ($this->observations->removeElement($observation)) {
            // set the owning side to null (unless already changed)
            if ($observation->getPatient() === $this) {
                $observation->setPatient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Appointment>
     */
    public function getAppointments(): Collection
    {
        return $this->appointments;
    }

    public function addAppointment(Appointment $appointment): self
    {
        if (!$this->appointments->contains($appointment)) {
            $this->appointments[] = $appointment;
            $appointment->setPatient($this);
        }

        return $this;
    }

    public function removeAppointment(Appointment $appointment): self
    {
        if ($this->appointments->removeElement($appointment)) {
            // set the owning side to null (unless already changed)
            if ($appointment->getPatient() === $this) {
                $appointment->setPatient(null);
            }
        }

        return $this;
    }
}
